# Generated by Django 2.0.4 on 2018-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioconvertapi', '0002_default_life_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioconvertjob',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bioconvertjob',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
