FROM debian:buster
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y \
        python3.6 \
        python3-pip \
        cython3 \
        gcc \
        libz-dev \
        nano \
        wget \
        gettext \
        apache2 \
        apache2-dev \
        python3.6-dev \
        cron \
 && rm -rf /var/lib/apt/lists/*
#    add-apt-repository ppa:deadsnakes/ppa && \
#    apt-get install software-properties-common -y && \
#    apt-get update && \

RUN pip3 install --upgrade pip && \
    pip3 install mod_wsgi

RUN a2enmod \
        ssl \
        wsgi \
        rewrite \
        expires \
        proxy_http \
 && a2dissite 000-default

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /code/
RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt

COPY ./resources/docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

COPY ./resources/django.conf /etc/apache2/sites-enabled/django.conf

# create unprivileged user
RUN adduser --disabled-password --gecos '' myuser

ADD . /code/
